FROM golang:alpine AS builder

WORKDIR /go/src/app
COPY . .

RUN go mod init
RUN go get -d -v
RUN go build -o /go/bin/fullcycle

FROM scratch
COPY --from=builder /go/bin/fullcycle /go/bin/fullcycle

CMD ["/go/bin/fullcycle"]